### ISSUE TITLE
Analysis killed on chr1

### ISSUE THREAD

**Issue by tolender** [BlanchetteLab/RefHiC#2]
I am trying RefHiC on a PC with 16GB RAM and an RTX2070 and the program crashed on the first chromosome before analysis.

_refhic tad pred --gpu 0 Test1_5kb.bcool Test1_output
use gpu cuda:0

Model: refhicNet-tad
Resolution: 5000
window size: 41

analyzing chromosome  chr1  ...
Killed_

When watching MSI Afterburner, I can see the GPU memory increase slightly but no gpu activity is visible. My RAM reaches 14GB for about a minute, then drops after being killed (usually).
I have also tried cpu mode, where it seems to get slightly farther but also crashes.

_$ refhic tad pred --cpu true Test1_5kb.bcool Test1_output
use CPU ...

Model: refhicNet-tad
Resolution: 5000
window size: 41

analyzing chromosome  chr1  ...
  0%|                                                                                                | 0/77 [00:00<?, ?it/s]
Killed_

**Comment by zhyanlin** [comment]
I think the crash is due to out of memory.  The best solution is to run RefHiC on a computer with a large RAM. Alternatively, You can try to reduce the batch size to 10 or even 5 to reduce memory footprint.

**Comment by tolender** [comment]
Seems the issue is probably on my end regarding the gpu config for WSL-linux and my limited RAM.
The batchsize suggestion was helpful, I did manage to run individual chromosomes using "--cpu true -t 1 --batchsize 1" which took about 5min per chromosome. I couldn't run all the chromosomes in a single run as chr1 would finish then crash when starting chr2.

I did run into a problem for about half of the chromosomes (chr13 - chr19 + chrX) however some of the chromosomes crashed about 90% in then throwing an error. Any idea what is happening here?

$ refhic tad pred --cpu true -t 1 --batchsize 1 --chrom chr13 Sample_5kb.bcool Sample_5kb.bcool.chr13
use CPU ...
***************************
Model: refhicNet-tad
Resolution: 5000
window size: 41
***************************
analyzing chromosome  chr13  ...
 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉          | 22792/24004 [03:40<00:11, 103.41it/s]
Traceback (most recent call last):
  File "/home/tom/software/anaconda3/envs/refhic/bin/refhic", line 33, in <module>
    sys.exit(load_entry_point('refhic', 'console_scripts', 'refhic')())
  File "/home/tom/software/anaconda3/envs/refhic/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/tom/software/anaconda3/envs/refhic/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/tom/software/anaconda3/envs/refhic/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tom/software/anaconda3/envs/refhic/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tom/software/anaconda3/envs/refhic/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tom/software/anaconda3/envs/refhic/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/tom/software/RefHiC/refhic/tadPred.py", line 185, in pred
    for X in tqdm(test_dataloader):
  File "/home/tom/software/anaconda3/envs/refhic/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/tom/software/anaconda3/envs/refhic/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/tom/software/anaconda3/envs/refhic/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/tom/software/anaconda3/envs/refhic/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/tom/software/anaconda3/envs/refhic/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/tom/software/anaconda3/envs/refhic/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/tom/software/anaconda3/envs/refhic/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/tom/software/anaconda3/envs/refhic/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/tom/software/RefHiC/refhic/data.py", line 100, in __getitem__
    mat, meta = self.extra[i].square(xCenter, yCenter, self.w, 'b',cache=False)
  File "/home/tom/software/RefHiC/refhic/bcooler.py", line 299, in square
    output = np.concatenate((tril_part, output), axis=-1)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 41 and the array at index 1 has size 40.

**Comment by zhyanlin** [comment]
it's weird. ??/24004 should be ??/22792. Is hg38 your reference genome? 
Our reference panel contains data aligned to hg38, and it only works with study samples aligned to hg38.

**Comment by tolender** [comment]
This sample is mm10, does the genome of the sample need to match the reference model genome? I thought your paper said the trained model for human can be used for mouse and other mammalian genomes.

**Comment by zhyanlin** [comment]
Yes and yes. But you need to use the correct reference panel. As mentioned in the readme file:

> If you want to use the mouse reference panel (mm10), you need to dowmload it from http://repo.cs.mcgill.ca/PUB/blanchem/RefHiC/mouseRefPanel.zip and deploy it by selecting option (2) load your own panel.

For other mammalian genomes, you need to create your own reference panel.

**Comment by tolender** [comment]
Thank you for the clarification and quick reply! I will try again and follow up.

**Comment by tolender** [comment]
I increased my RAM from 16GB up to 32GB, now the gpu is being initialized properly and all chromosomes are running in sequence in a single run, I am also using the correct models for hg38 and mm10.
Thank you for the help!
